package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;

import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.LayoutStyle.ComponentPlacement;

import entities.Ameaca;
import services.AmeacaService;

import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JSpinner;
/**
 *
 * @author Vinicius
 */
public class cad_ameaca extends javax.swing.JDialog {
    private ExecutarCadastro executarCadastro;
    private Ameaca ameaca;
    private AmeacaService ameacaService = new AmeacaService();
    private boolean confirmado;
    
    /**
     * Creates new form cad_ameaca
     * @wbp.parser.constructor
     */
    public cad_ameaca(java.awt.Frame parent, ExecutarCadastro executarCadastro, Ameaca ameaca) {
        super(parent, true);
        confirmado = false;
        this.executarCadastro = executarCadastro;
        this.ameaca = ameaca;
        initComponents();
        if(executarCadastro == executarCadastro.atualizar || executarCadastro == ExecutarCadastro.consultar) {
        	
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            aNumCve.setText(this.ameaca.getCve());
            aVersao.setText(ameaca.getVersao());
            aTipo.setText(ameaca.getTipo());
            aCriticidade.setText(ameaca.getCriticidade());
            aData.setText(dateFormat.format(ameaca.getData()));
            aPathCorrecao.setText(ameaca.getPathCorrecao().getName());
            aSolucao.setText(ameaca.getSolucao().getName());
            aConsequencia.setText(ameaca.getConsequencia().getName());
        }
    }
    
    public boolean confirmar() {
        return confirmado;
    }
    
    public static boolean executar(java.awt.Frame parent, ExecutarCadastro executarCadastro, Ameaca ameaca) {
        cad_ameaca tela = new cad_ameaca(parent, executarCadastro, ameaca);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        return tela.confirmar();
    }
    
    public cad_ameaca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aNumCve = new javax.swing.JTextField();
        aProduto = new javax.swing.JTextField();
        aVersao = new javax.swing.JTextField();
        aTipo = new javax.swing.JTextField();
        aCriticidade = new javax.swing.JTextField();
        aData = new javax.swing.JTextField();
        aPathCorrecao = new javax.swing.JTextField();
        aSolucao = new javax.swing.JTextField();
        aConsequencia = new javax.swing.JTextField();
        buttonConfirmar = new javax.swing.JButton();
        buttonSolucao = new javax.swing.JButton();
        buttonPathCorrecao = new javax.swing.JButton();
        buttonConsequencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aNumCve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNumCveActionPerformed(evt);
            }
        });

        buttonConfirmar.setText("confirmar");
        buttonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmarActionPerformed(ameaca);
            }
        });
        
        buttonConsequencia.setText("Consequencia");
        buttonConsequencia.addActionListener(new ActionListener() {
	      public void actionPerformed(ActionEvent ae) {
	        JFileChooser fileChooser = new JFileChooser();
	        int returnValue = fileChooser.showOpenDialog(null);
	        if (returnValue == JFileChooser.APPROVE_OPTION) 
	        	ameaca.setConsequencia(fileChooser.getSelectedFile());
	      }
	    });
		    
        buttonSolucao.setText("Solucao");
        buttonSolucao.addActionListener(new ActionListener() {
  	      public void actionPerformed(ActionEvent ae) {
  	        JFileChooser fileChooser = new JFileChooser();
  	        int returnValue = fileChooser.showOpenDialog(null);
  	        if (returnValue == JFileChooser.APPROVE_OPTION) 
  	        	ameaca.setSolucao(fileChooser.getSelectedFile());
  	      }
  	    });
        
        buttonPathCorrecao.setText("Path Correcao");
        buttonPathCorrecao.addActionListener(new ActionListener() {
  	      public void actionPerformed(ActionEvent ae) {
  	        JFileChooser fileChooser = new JFileChooser();
  	        int returnValue = fileChooser.showOpenDialog(null);
  	        if (returnValue == JFileChooser.APPROVE_OPTION) 
  	        	ameaca.setPathCorrecao(fileChooser.getSelectedFile());
  	      }
  	    });
        
        jLabel1.setText("Número CVE");

        jLabel2.setText("Produto:");

        jLabel3.setText("Versão:");

        jLabel4.setText("Tipo");

        jLabel5.setText("Criticidade:");

        jLabel6.setText("Data:");
        
        jLabel7.setText("Path Correção");
        
        jLabel8.setText("Solução");
        
        jLabel9.setText("Consequência");
        
        //JButton button = new JButton("Selecionar");
        
        JList list = new JList();
        
        JList list_1 = new JList();
	    
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(223, Short.MAX_VALUE)
        			.addComponent(buttonConfirmar)
        			.addGap(26))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(34)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				//.addComponent(jLabel8)
        				.addComponent(buttonSolucao)
        				//.addComponent(jLabel9)
        				.addGap(5, 10,   50)
        				.addComponent(buttonConsequencia)
        				//.addComponent(jLabel7)
        				.addComponent(buttonPathCorrecao)
        				.addComponent(jLabel6)
        				.addComponent(jLabel5)
        				.addComponent(jLabel4)
        				.addComponent(jLabel3)
        				.addComponent(jLabel2)
        				.addComponent(jLabel1))
        			.addGap(26)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(75)
        					.addComponent(list_1, GroupLayout.PREFERRED_SIZE, 1, GroupLayout.PREFERRED_SIZE))
        				.addComponent(aNumCve, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aProduto, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aVersao, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aTipo, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aCriticidade, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(aData, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				//.addComponent(aPathCorrecao, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				//.addComponent(aSolucao, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				//.addComponent(aConsequencia, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				)
        			.addContainerGap(47, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(138)
        			.addComponent(list, GroupLayout.PREFERRED_SIZE, 1, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(27)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(list, GroupLayout.PREFERRED_SIZE, 1, GroupLayout.PREFERRED_SIZE)
        				.addComponent(list_1, GroupLayout.PREFERRED_SIZE, 1, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aNumCve, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aProduto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aVersao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aCriticidade, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aData, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6))
        			.addPreferredGap(ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				//.addComponent(aPathCorrecao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				//.addComponent(jLabel7)
        					.addComponent(buttonPathCorrecao)
        					)
        					
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				/*.addComponent(aSolucao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8)
        				 */
        				)
        			.addComponent(buttonSolucao)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
    					/*.addComponent(aConsequencia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
    					.addComponent(jLabel9)*/
        				.addComponent(buttonConsequencia))
        			.addGap(18)
        			.addComponent(buttonConfirmar)
        			.addGap(26))
        );
        
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirmarActionPerformed(Ameaca ameaca) {//GEN-FIRST:event_buttonConfirmarActionPerformed
    	System.out.println("TESTE: "+ aNumCve.getText());
        if(executarCadastro != ExecutarCadastro.consultar) {
            ameaca.setCve(aNumCve.getText());
            ameaca.setProduto(aProduto.getText());
            ameaca.setVersao(aVersao.getText());
            ameaca.setTipo(aTipo.getText());
            ameaca.setCriticidade(aCriticidade.getText());
            ameaca.setData(new Date(aData.getText()));
                
            ameacaService.inserir(ameaca);
            
            confirmado = true;
        }
        dispose();
    }//GEN-LAST:event_buttonConfirmarActionPerformed

    private void aNumCveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:aNumCveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:aNumCveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cad_ameaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cad_ameaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cad_ameaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cad_ameaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cad_ameaca dialog = new cad_ameaca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonConfirmar;
    private javax.swing.JButton buttonSolucao;
    private javax.swing.JButton buttonPathCorrecao;
    private javax.swing.JButton buttonConsequencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField aNumCve;
    private javax.swing.JTextField aProduto;
    private javax.swing.JTextField aVersao;
    private javax.swing.JTextField aTipo;
    private javax.swing.JTextField aCriticidade;
    private javax.swing.JTextField aData;
    private javax.swing.JTextField aPathCorrecao;
    private javax.swing.JTextField aSolucao;
    private javax.swing.JTextField aConsequencia;
}

