/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import trabalho_prj.Ameaca;
import view.Sobre;
import view.Tabela;
import view.entrar;

import javax.swing.JPanel;
import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.border.TitledBorder;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.MatteBorder;
import java.awt.Toolkit;
import javax.swing.JSlider;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import javax.swing.JInternalFrame;
import javax.swing.JTextArea;
import java.awt.TextField;
import java.awt.TextArea;
import javax.swing.JLayeredPane;
import javax.swing.JButton;
import javax.swing.UIManager;
import javax.swing.JMenuBar;
import java.awt.SystemColor;
import javax.swing.JMenu;
import javax.swing.JToolBar;
import javax.swing.JTextField;
import java.awt.Label;
import javax.swing.JEditorPane;
import javax.swing.JTextPane;
import java.awt.Cursor;

/**
 *
 * @author Vinicius
 */
public class entrar extends javax.swing.JDialog {

    /**
     * Creates new form entrar
     */
    public entrar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setForeground(UIManager.getColor("CheckBox.interiorBackground"));
        getContentPane().setBackground(UIManager.getColor("CheckBox.background"));
        
        JMenuBar menuBar = new JMenuBar();
        menuBar.setForeground(UIManager.getColor("CheckBox.foreground"));
        menuBar.setBackground(UIManager.getColor("CheckBox.focus"));
        setJMenuBar(menuBar);
        jButton1 = new javax.swing.JButton();
        menuBar.add(jButton1);
        
                jButton1.setBackground(Color.DARK_GRAY);
                jButton1.setFont(new Font("Inter", Font.PLAIN, 11)); // NOI18N
                jButton1.setForeground(Color.WHITE);
                jButton1.setText("cadastrar");
                jButton1.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                
                JButton btnSobre = new JButton("sobre");
                btnSobre.setFont(new Font("Inter", Font.PLAIN, 11));
                btnSobre.setForeground(Color.WHITE);
                btnSobre.setBackground(Color.DARK_GRAY);
                menuBar.add(btnSobre);
                
                btnSobre.addActionListener(new java.awt.event.ActionListener() {
                	public void actionPerformed(java.awt.event.ActionEvent evt) {
                		Sobre.exibirTelaSobre();
                	}
                });
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
        initComponents();
        setResizable(false);
        setPreferredSize(new java.awt.Dimension(300, 300));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setBackground(UIManager.getColor("Button.shadow"));
        
        JLayeredPane layeredPane = new JLayeredPane();
        
        JLabel lblNewLabel = new JLabel("CADASTRAR AMEAÇAS");
        lblNewLabel.setFont(new Font("Inter ExtraBold", Font.PLAIN, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(100)
        					.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(42)
        					.addComponent(lblNewLabel)))
        			.addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(66)
        			.addComponent(lblNewLabel)
        			.addGap(263)
        			.addComponent(layeredPane, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        getContentPane().setLayout(layout);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tabela obj = new Tabela(null, true);
        obj.setLocationRelativeTo(null);
        obj.setVisible(true);
        
        Ameaca ameaca= new Ameaca();
        ameaca.abrir();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                entrar dialog = new entrar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowAdapter e) {
                        System.exit(0);
                    }
                });
                dialog.pack();
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jMenuItem1;
}